site_name: MacServer Documentation
site_url: https://andrewbreyen.github.io/MacServer-Documentation/
nav:
    - Home: index.md
    - Setup:
      - 'First Time Setup': 'setup/first-time-setup.md'
      - 'Ventura First Time Setup': 'setup/first-time-setup-ventura.md'
      - 'macOS Settings': 'setup/macos-settings.md'
      - 'Jumpcloud': 'setup/jumpcloud.md'
      - 'Apple Remote Desktop': 'setup/apple-remote-desktop.md'
      - 'Installs': 'setup/installs.md'
    - Server Apps:
      - 'macOS Server': 'server-apps/macos-server.md'
      - 'Docker': 'server-apps/docker.md'
      - 'TeamViewer': 'server-apps/teamviewer.md'
      - 'Jellyfin': 'server-apps/jellyfin.md'
      - 'Homebridge': 'server-apps/homebridge.md'
      - 'Home Assistant': 'server-apps/homeassistant.md'
      - 'Scrypted': 'server-apps/scrypted.md'
      - 'Node-RED': 'server-apps/node-red.md'
      - 'Pihole': 'server-apps/pihole.md'
      - 'Tdarr': 'server-apps/tdarr.md'
      - 'Time Machine Editor': 'server-apps/timemachine-editor.md'
    - Hardware:
      - 'Hardware': 'hardware/hardware.md'
      - 'Zigbee-Conbee': 'hardware/zigbee-conbee.md'
    - Troubleshooting:
      - 'Reboot': 'troubleshooting/reboot.md'
      - 'Live TV Guide Data Issues': 'troubleshooting/live-tv-data-issues.md'
      - 'Smart Devices showing as “No Response”/Orange Exclamation mark': 'troubleshooting/no-response-homekit.md'
      - 'Network Change: Smart Home Devices': 'troubleshooting/network-change-smart-home.md'
      - 'Ventura Update: Issues and Solutions': 'troubleshooting/ventura-update.md'
theme:
  name: material
  logo: img/macmini-icon.png
  favicon: img/macmini-icon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox
  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
copyright: "<a href=/MacServer-Documentation/attributions>Attributions</a>"