name: MKDocsBuildDeploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: MKDocsBuildDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Linting
        run: |
          markdownlint . --config .mdlrc .

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest"
          requirements: "requirements.txt"
          configfile: "mkdocs.yml"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
