name: MKDocsBuildDeploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: MKDocsBuildDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Linting
        run: |
          markdownlint . --config .mdlrc .

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest"
          requirements: "requirements.txt"
          configfile: "mkdocs.yml"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  post-to-slack:
    name: Post to Slack channel
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel ID where the message will be posted. Needed if using a bot token
          channel-id: "C05JB2CA4SE"
          # Message to post into Slack. Needed if using a bot token
          payload: |
            {
              "text": "MacSetup build and deploy result:${{ needs.build.result }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "MacSetup build and deploy result:\n${{ needs.build.result }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
