name: Lint

on:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install prettier
      - name: Install prettier
        run: npm install -g prettier

      # Lint with prettier and markdownlintm
      - name: Run Prettier
        run: |
          echo "### Prettier:"
          prettier --list-different "docs/*.md" --log-level=warn

      - uses: DavidAnson/markdownlint-cli2-action@v11
  

      # Check if any changes were made after prettier formatting
      - name: Check for Changes
        run: |
          git diff --exit-code || (echo "Linting/formatting changes found. Please commit and push the changes." && false)
