name: Lint

on:
  push:
    branches:
      - "main"
      - '**/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: prettier
        uses: actionsx/prettier@v2
        with:
        # prettier CLI arguments.
          args: --check "**/*.md"

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'
  

      # Check if any changes were made after prettier formatting
      - name: Check for Changes
        run: |
          git diff --exit-code || (echo "Linting/formatting changes found. Please commit and push the changes." && false)
