name: Lint

on:
  push:
    branches:
      - "main"
      - "**/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: prettier
        uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check "**/*.md"

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: "**/*.md"

      # Check if any changes were made after prettier formatting
      - name: Check for Changes
        run: |
          git diff --exit-code || (echo "Linting/formatting changes found. Please commit and push the changes." && false)

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel ID where message will be posted. Needed if using bot token
          channel-id: "C04JZM55VC2"
          # Message to post into Slack. Needed if using bot token
          payload: |
            {
              "text": "mac-setup Lint result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "mac-setup Lint result:\n${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
