name: Deploy mkdocs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  buildupload:
    name: Build mkdocs site upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs-version: "latest" # option
          #mkdocs-version: '1.1' # option
          requirements: "requirements.txt" # option
          configfile: "mkdocs.yml" # option

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}

      # - name: UploadS3
      #   uses: noveto-com/s3-upload-sha256-action@main
      #   with:
      #     args: --acl public-read --follow-symlinks
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     SOURCE_DIR: 'public'
