name: MKDocsBuildDeploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: MKDocsBuildDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest"
          requirements: "requirements.txt"
          configfile: "mkdocs.yml"

      # Download the lint-results artifact from the lint job
      - name: Download Linting Results
        uses: actions/download-artifact@v2
        with:
          name: lint-results
          path: lint-results

      # Check if the linting report contains any errors
      - name: Check Linting Results
        run: |
          if grep -q "error" lint-results/linting-report.txt; then
            echo "Linting failed. Please fix the errors before deploying."
            exit 1
          else
            echo "Linting successful. Proceeding with the deployment."
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
